"""replace admin flag with organization administrator

Revision ID: 044a88183565
Revises: 624b1ac80146
Create Date: 2026-09-17 17:16:37.805553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044a88183565'
down_revision: Union[str, Sequence[str], None] = '624b1ac80146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('organizations', sa.Column('administrator_user_id', sa.UUID(), nullable=True))
    # op.create_index(op.f('ix_organizations_administrator_user_id'), 'organizations', ['administrator_user_id'], unique=False)
    # op.create_foreign_key('fk_organizations_admin_same_org', 'organizations', 'users', ['administrator_user_id', 'id'], ['id', 'organization_id'])
    # op.drop_index(op.f('uq_users_one_organization_admin'), table_name='users', postgresql_where='(is_organization_admin IS TRUE)')
    # op.create_unique_constraint('uq_users_id_organization', 'users', ['id', 'organization_id'])
    # op.drop_column('users', 'is_organization_admin')

    op.add_column(
        "organizations",
        sa.Column(
            "administrator_user_id",
            sa.UUID(),
            nullable=True,
        ),
    )

    op.create_index(
        op.f("ix_organizations_administrator_user_id"),
        "organizations",
        ["administrator_user_id"],
        unique=False,
    )

    op.create_unique_constraint(
        "uq_users_id_organization",
        "users",
        ["id", "organization_id"],
    )

    op.create_foreign_key(
        "fk_organizations_admin_same_org",
        "organizations",
        "users",
        ["administrator_user_id", "id"],
        ["id", "organization_id"],
    )

    op.drop_index(
        op.f("uq_users_one_organization_admin"),
        table_name="users",
        postgresql_where="(is_organization_admin IS TRUE)",
    )

    op.drop_column(
        "users",
        "is_organization_admin",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('is_organization_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # op.drop_constraint('uq_users_id_organization', 'users', type_='unique')
    # op.create_index(op.f('uq_users_one_organization_admin'), 'users', ['organization_id'], unique=True, postgresql_where='(is_organization_admin IS TRUE)')
    # op.drop_constraint('fk_organizations_admin_same_org', 'organizations', type_='foreignkey')
    # op.drop_index(op.f('ix_organizations_administrator_user_id'), table_name='organizations')
    # op.drop_column('organizations', 'administrator_user_id')

    op.add_column(
        "users",
        sa.Column(
            "is_organization_admin",
            sa.BOOLEAN(),
            nullable=True,
        ),
    )

    op.drop_constraint(
        "fk_organizations_admin_same_org",
        "organizations",
        type_="foreignkey",
    )

    op.drop_index(
        op.f("ix_organizations_administrator_user_id"),
        table_name="organizations",
    )

    op.drop_column(
        "organizations",
        "administrator_user_id",
    )

    op.drop_constraint(
        "uq_users_id_organization",
        "users",
        type_="unique",
    )

    op.execute(
        "UPDATE users SET is_organization_admin = FALSE "
        "WHERE is_organization_admin IS NULL"
    )

    op.alter_column(
        "users",
        "is_organization_admin",
        nullable=False,
    )

    op.create_index(
        op.f("uq_users_one_organization_admin"),
        "users",
        ["organization_id"],
        unique=True,
        postgresql_where="(is_organization_admin IS TRUE)",
    )
    # ### end Alembic commands ###
