"""add appointment services

Revision ID: 099a5004493c
Revises: c2335207f47e
Create Date: 2026-09-21 17:04:03.197829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099a5004493c'
down_revision: Union[str, Sequence[str], None] = 'c2335207f47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('branch_service_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_appointment_services_duration'),
    sa.CheckConstraint('quantity > 0', name='ck_appointment_services_quantity'),
    sa.CheckConstraint('unit_price >= 0', name='ck_appointment_services_unit_price'),
    sa.ForeignKeyConstraint(['appointment_id', 'organization_id'], ['appointments.id', 'appointments.organization_id'], name='fk_appointment_services_appointment'),
    sa.ForeignKeyConstraint(['branch_service_id', 'organization_id', 'branch_id'], ['branch_services.id', 'branch_services.organization_id', 'branch_services.branch_id'], name='fk_appointment_services_branch_service'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_appointment_services_id_organization')
    )
    op.create_index(op.f('ix_appointment_services_appointment_id'), 'appointment_services', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_services_branch_id'), 'appointment_services', ['branch_id'], unique=False)
    op.create_index(op.f('ix_appointment_services_branch_service_id'), 'appointment_services', ['branch_service_id'], unique=False)
    op.create_index(op.f('ix_appointment_services_organization_id'), 'appointment_services', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_services_organization_id'), table_name='appointment_services')
    op.drop_index(op.f('ix_appointment_services_branch_service_id'), table_name='appointment_services')
    op.drop_index(op.f('ix_appointment_services_branch_id'), table_name='appointment_services')
    op.drop_index(op.f('ix_appointment_services_appointment_id'), table_name='appointment_services')
    op.drop_table('appointment_services')
    # ### end Alembic commands ###
