"""add resource work schedules

Revision ID: 1d0be68e5659
Revises: 977dbaf3b4b3
Create Date: 2026-09-21 16:40:27.872990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0be68e5659'
down_revision: Union[str, Sequence[str], None] = '977dbaf3b4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_work_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='ck_resource_work_schedules_day'),
    sa.CheckConstraint('starts_at < ends_at', name='ck_resource_work_schedules_times'),
    sa.ForeignKeyConstraint(['resource_id', 'organization_id', 'branch_id'], ['resources.id', 'resources.organization_id', 'resources.branch_id'], name='fk_rws_resource'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_resource_work_schedules_id_organization')
    )
    op.create_index(op.f('ix_resource_work_schedules_branch_id'), 'resource_work_schedules', ['branch_id'], unique=False)
    op.create_index(op.f('ix_resource_work_schedules_organization_id'), 'resource_work_schedules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_resource_work_schedules_resource_id'), 'resource_work_schedules', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_work_schedules_resource_id'), table_name='resource_work_schedules')
    op.drop_index(op.f('ix_resource_work_schedules_organization_id'), table_name='resource_work_schedules')
    op.drop_index(op.f('ix_resource_work_schedules_branch_id'), table_name='resource_work_schedules')
    op.drop_table('resource_work_schedules')
    # ### end Alembic commands ###
