"""add customer contact points

Revision ID: 25923a268bc2
Revises: 773baa35e2bf
Create Date: 2026-09-21 14:03:11.327197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25923a268bc2'
down_revision: Union[str, Sequence[str], None] = '773baa35e2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_contact_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('contact_point_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_point_id', 'organization_id'], ['contact_points.id', 'contact_points.organization_id'], name='fk_customer_contact_points_contact_point_same_org'),
    sa.ForeignKeyConstraint(['customer_id', 'organization_id'], ['customers.id', 'customers.organization_id'], name='fk_customer_contact_points_customer_same_org'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'customer_id', 'contact_point_id', name='uq_customer_contact_points_customer_contact')
    )
    op.create_index(op.f('ix_customer_contact_points_contact_point_id'), 'customer_contact_points', ['contact_point_id'], unique=False)
    op.create_index(op.f('ix_customer_contact_points_customer_id'), 'customer_contact_points', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_contact_points_organization_id'), 'customer_contact_points', ['organization_id'], unique=False)
    op.create_index('uq_customer_contact_points_primary', 'customer_contact_points', ['organization_id', 'customer_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_customer_contact_points_primary', table_name='customer_contact_points', postgresql_where=sa.text('is_primary = true'))
    op.drop_index(op.f('ix_customer_contact_points_organization_id'), table_name='customer_contact_points')
    op.drop_index(op.f('ix_customer_contact_points_customer_id'), table_name='customer_contact_points')
    op.drop_index(op.f('ix_customer_contact_points_contact_point_id'), table_name='customer_contact_points')
    op.drop_table('customer_contact_points')
    # ### end Alembic commands ###
