"""add service skill requirements

Revision ID: 2756d20276e8
Revises: 2d3b2a17e7c4
Create Date: 2026-09-21 13:07:39.579760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2756d20276e8'
down_revision: Union[str, Sequence[str], None] = '2d3b2a17e7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_skill_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['service_id', 'organization_id'], ['services.id', 'services.organization_id'], name='fk_service_skill_requirements_service_same_org'),
    sa.ForeignKeyConstraint(['skill_id', 'organization_id'], ['skills.id', 'skills.organization_id'], name='fk_service_skill_requirements_skill_same_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'service_id', 'skill_id', name='uq_service_skill_requirements_service_skill')
    )
    op.create_index(op.f('ix_service_skill_requirements_organization_id'), 'service_skill_requirements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_service_skill_requirements_service_id'), 'service_skill_requirements', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_skill_requirements_skill_id'), 'service_skill_requirements', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_skill_requirements_skill_id'), table_name='service_skill_requirements')
    op.drop_index(op.f('ix_service_skill_requirements_service_id'), table_name='service_skill_requirements')
    op.drop_index(op.f('ix_service_skill_requirements_organization_id'), table_name='service_skill_requirements')
    op.drop_table('service_skill_requirements')
    # ### end Alembic commands ###
