"""create roles table

Revision ID: 2b24bd953f74
Revises: eee81a291e6f
Create Date: 2026-09-17 18:06:55.490935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b24bd953f74'
down_revision: Union[str, Sequence[str], None] = 'eee81a291e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_organization_id'), 'roles', ['organization_id'], unique=False)
    op.create_index('uq_roles_organization_code', 'roles', ['organization_id', 'code'], unique=True, postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.create_index('uq_roles_organization_name', 'roles', ['organization_id', 'name'], unique=True, postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.create_index('uq_roles_system_code', 'roles', ['code'], unique=True, postgresql_where=sa.text('organization_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_roles_system_code', table_name='roles', postgresql_where=sa.text('organization_id IS NULL'))
    op.drop_index('uq_roles_organization_name', table_name='roles', postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.drop_index('uq_roles_organization_code', table_name='roles', postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.drop_index(op.f('ix_roles_organization_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
