"""add customer relationship types

Revision ID: 38e7dd26664d
Revises: 25923a268bc2
Create Date: 2026-09-21 14:53:14.071677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e7dd26664d'
down_revision: Union[str, Sequence[str], None] = '25923a268bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_relationship_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_customer_relationship_types_id_organization'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_customer_relationship_types_organization_code'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_customer_relationship_types_organization_name')
    )
    op.create_index('ix_customer_relationship_types_organization_id', 'customer_relationship_types', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_relationship_types_organization_id', table_name='customer_relationship_types')
    op.drop_table('customer_relationship_types')
    # ### end Alembic commands ###
