"""add appointment service employees

Revision ID: 465e76903ada
Revises: 099a5004493c
Create Date: 2026-09-21 17:09:19.635076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465e76903ada'
down_revision: Union[str, Sequence[str], None] = '099a5004493c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_service_employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('appointment_service_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_service_id', 'organization_id'], ['appointment_services.id', 'appointment_services.organization_id'], name='fk_appointment_service_employees_service'),
    sa.ForeignKeyConstraint(['branch_id', 'organization_id'], ['branches.id', 'branches.organization_id'], name='fk_appointment_service_employees_branch'),
    sa.ForeignKeyConstraint(['employee_id', 'organization_id'], ['employees.id', 'employees.organization_id'], name='fk_appointment_service_employees_employee'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_appointment_service_employees_id_organization'),
    sa.UniqueConstraint('organization_id', 'appointment_service_id', 'employee_id', name='uq_appointment_service_employees_service_employee')
    )
    op.create_index(op.f('ix_appointment_service_employees_appointment_service_id'), 'appointment_service_employees', ['appointment_service_id'], unique=False)
    op.create_index(op.f('ix_appointment_service_employees_branch_id'), 'appointment_service_employees', ['branch_id'], unique=False)
    op.create_index(op.f('ix_appointment_service_employees_employee_id'), 'appointment_service_employees', ['employee_id'], unique=False)
    op.create_index(op.f('ix_appointment_service_employees_organization_id'), 'appointment_service_employees', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_service_employees_organization_id'), table_name='appointment_service_employees')
    op.drop_index(op.f('ix_appointment_service_employees_employee_id'), table_name='appointment_service_employees')
    op.drop_index(op.f('ix_appointment_service_employees_branch_id'), table_name='appointment_service_employees')
    op.drop_index(op.f('ix_appointment_service_employees_appointment_service_id'), table_name='appointment_service_employees')
    op.drop_table('appointment_service_employees')
    # ### end Alembic commands ###
