"""add employee schedule exceptions

Revision ID: 5cce9220dd88
Revises: aeeb6f4a2512
Create Date: 2026-09-21 16:06:13.568464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cce9220dd88'
down_revision: Union[str, Sequence[str], None] = 'aeeb6f4a2512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_schedule_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('exception_type', sa.Enum('OFF', 'WORK', name='employee_schedule_exception_type'), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=True),
    sa.Column('ends_at', sa.Time(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(exception_type = 'OFF' AND starts_at IS NULL AND ends_at IS NULL) OR (exception_type = 'OFF' AND starts_at IS NOT NULL AND ends_at IS NOT NULL AND starts_at < ends_at) OR (exception_type = 'WORK' AND starts_at IS NOT NULL AND ends_at IS NOT NULL AND starts_at < ends_at)", name='ck_employee_schedule_exceptions_type_times'),
    sa.ForeignKeyConstraint(['branch_id', 'organization_id'], ['branches.id', 'branches.organization_id'], name='fk_employee_schedule_exceptions_branch_same_org'),
    sa.ForeignKeyConstraint(['employee_id', 'organization_id'], ['employees.id', 'employees.organization_id'], name='fk_employee_schedule_exceptions_employee_same_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_employee_schedule_exceptions_id_organization')
    )
    op.create_index(op.f('ix_employee_schedule_exceptions_branch_id'), 'employee_schedule_exceptions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_employee_schedule_exceptions_employee_id'), 'employee_schedule_exceptions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_schedule_exceptions_exception_date'), 'employee_schedule_exceptions', ['exception_date'], unique=False)
    op.create_index(op.f('ix_employee_schedule_exceptions_organization_id'), 'employee_schedule_exceptions', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_schedule_exceptions_organization_id'), table_name='employee_schedule_exceptions')
    op.drop_index(op.f('ix_employee_schedule_exceptions_exception_date'), table_name='employee_schedule_exceptions')
    op.drop_index(op.f('ix_employee_schedule_exceptions_employee_id'), table_name='employee_schedule_exceptions')
    op.drop_index(op.f('ix_employee_schedule_exceptions_branch_id'), table_name='employee_schedule_exceptions')
    op.drop_table('employee_schedule_exceptions')
    # ### end Alembic commands ###
