"""Add organization validity and admin flag

Revision ID: 624b1ac80146
Revises: 44b12592d179
Create Date: 2026-09-17 12:49:58.796314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624b1ac80146'
down_revision: Union[str, Sequence[str], None] = '44b12592d179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('validity_until', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('is_organization_admin', sa.Boolean(), nullable=False))
    op.create_index('uq_users_one_organization_admin', 'users', ['organization_id'], unique=True, postgresql_where=sa.text('is_organization_admin IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_one_organization_admin', table_name='users', postgresql_where=sa.text('is_organization_admin IS true'))
    op.drop_column('users', 'is_organization_admin')
    op.drop_column('organizations', 'validity_until')
    # ### end Alembic commands ###
