"""add branch business hours

Revision ID: 63907bd65380
Revises: 9f5125f65991
Create Date: 2026-09-21 15:39:34.453397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63907bd65380'
down_revision: Union[str, Sequence[str], None] = '9f5125f65991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_business_hours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_closed = true AND opens_at IS NULL AND closes_at IS NULL) OR (is_closed = false AND opens_at IS NOT NULL AND closes_at IS NOT NULL AND opens_at < closes_at)', name='ck_branch_business_hours_times'),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='ck_branch_business_hours_day_of_week'),
    sa.ForeignKeyConstraint(['branch_id', 'organization_id'], ['branches.id', 'branches.organization_id'], name='fk_branch_business_hours_branch_same_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_branch_business_hours_id_organization')
    )
    op.create_index(op.f('ix_branch_business_hours_branch_id'), 'branch_business_hours', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_business_hours_organization_id'), 'branch_business_hours', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branch_business_hours_organization_id'), table_name='branch_business_hours')
    op.drop_index(op.f('ix_branch_business_hours_branch_id'), table_name='branch_business_hours')
    op.drop_table('branch_business_hours')
    # ### end Alembic commands ###
