"""add employee skills

Revision ID: 72b6b7897120
Revises: 87c78978e7a2
Create Date: 2026-09-21 12:35:46.025145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b6b7897120'
down_revision: Union[str, Sequence[str], None] = '87c78978e7a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id', 'organization_id'], ['employees.id', 'employees.organization_id'], name='fk_employee_skills_employee_same_org'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['skill_id', 'organization_id'], ['skills.id', 'skills.organization_id'], name='fk_employee_skills_skill_same_org'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_skills_employee_id'), 'employee_skills', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_organization_id'), 'employee_skills', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_skill_id'), 'employee_skills', ['skill_id'], unique=False)
    op.create_index('uq_employee_skills_active', 'employee_skills', ['organization_id', 'employee_id', 'skill_id'], unique=True, postgresql_where=sa.text('to_date IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_employee_skills_active', table_name='employee_skills', postgresql_where=sa.text('to_date IS NULL'))
    op.drop_index(op.f('ix_employee_skills_skill_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_organization_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_employee_id'), table_name='employee_skills')
    op.drop_table('employee_skills')
    # ### end Alembic commands ###
