"""add customer relationships

Revision ID: 7ee5b1333234
Revises: 38e7dd26664d
Create Date: 2026-09-21 15:01:13.697868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee5b1333234'
down_revision: Union[str, Sequence[str], None] = '38e7dd26664d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('related_customer_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('customer_id <> related_customer_id', name='ck_customer_relationships_no_self'),
    sa.ForeignKeyConstraint(['customer_id', 'organization_id'], ['customers.id', 'customers.organization_id'], name='fk_customer_relationships_customer_same_org'),
    sa.ForeignKeyConstraint(['related_customer_id', 'organization_id'], ['customers.id', 'customers.organization_id'], name='fk_customer_relationships_related_customer_same_org'),
    sa.ForeignKeyConstraint(['relationship_type_id', 'organization_id'], ['customer_relationship_types.id', 'customer_relationship_types.organization_id'], name='fk_customer_relationships_type_same_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_customer_relationships_id_organization')
    )
    op.create_index(op.f('ix_customer_relationships_customer_id'), 'customer_relationships', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_relationships_organization_id'), 'customer_relationships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_customer_relationships_related_customer_id'), 'customer_relationships', ['related_customer_id'], unique=False)
    op.create_index(op.f('ix_customer_relationships_relationship_type_id'), 'customer_relationships', ['relationship_type_id'], unique=False)
    op.create_index('uq_customer_relationships_active', 'customer_relationships', ['organization_id', 'customer_id', 'related_customer_id', 'relationship_type_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_customer_relationships_active', table_name='customer_relationships', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_customer_relationships_relationship_type_id'), table_name='customer_relationships')
    op.drop_index(op.f('ix_customer_relationships_related_customer_id'), table_name='customer_relationships')
    op.drop_index(op.f('ix_customer_relationships_organization_id'), table_name='customer_relationships')
    op.drop_index(op.f('ix_customer_relationships_customer_id'), table_name='customer_relationships')
    op.drop_table('customer_relationships')
    # ### end Alembic commands ###
