"""add appointment events

Revision ID: 8c92ed5765e9
Revises: b6f32d40dcce
Create Date: 2026-09-21 19:47:14.617943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c92ed5765e9'
down_revision: Union[str, Sequence[str], None] = 'b6f32d40dcce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'BOOKED', 'CONFIRMED', 'RESCHEDULED', 'CHECKED_IN', 'STARTED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointment_event_type'), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id', 'organization_id'], ['appointments.id', 'appointments.organization_id'], name='fk_appointment_events_appointment'),
    sa.ForeignKeyConstraint(['created_by_user_id', 'organization_id'], ['users.id', 'users.organization_id'], name='fk_appointment_events_created_by_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_appointment_events_id_organization')
    )
    op.create_index(op.f('ix_appointment_events_appointment_id'), 'appointment_events', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_events_created_by_user_id'), 'appointment_events', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_appointment_events_event_at'), 'appointment_events', ['event_at'], unique=False)
    op.create_index(op.f('ix_appointment_events_event_type'), 'appointment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_appointment_events_organization_id'), 'appointment_events', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_events_organization_id'), table_name='appointment_events')
    op.drop_index(op.f('ix_appointment_events_event_type'), table_name='appointment_events')
    op.drop_index(op.f('ix_appointment_events_event_at'), table_name='appointment_events')
    op.drop_index(op.f('ix_appointment_events_created_by_user_id'), table_name='appointment_events')
    op.drop_index(op.f('ix_appointment_events_appointment_id'), table_name='appointment_events')
    op.drop_table('appointment_events')
    # ### end Alembic commands ###
