"""add resource schedule exceptions

Revision ID: 90c13ac40567
Revises: 1d0be68e5659
Create Date: 2026-09-21 16:50:51.968544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c13ac40567'
down_revision: Union[str, Sequence[str], None] = '1d0be68e5659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_schedule_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('exception_type', sa.Enum('OFF', 'WORK', name='resource_schedule_exception_type'), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=True),
    sa.Column('ends_at', sa.Time(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(exception_type = 'OFF' AND starts_at IS NULL AND ends_at IS NULL) OR (exception_type = 'OFF' AND starts_at IS NOT NULL AND ends_at IS NOT NULL AND starts_at < ends_at) OR (exception_type = 'WORK' AND starts_at IS NOT NULL AND ends_at IS NOT NULL AND starts_at < ends_at)", name='ck_rse_type_times'),
    sa.ForeignKeyConstraint(['resource_id', 'organization_id', 'branch_id'], ['resources.id', 'resources.organization_id', 'resources.branch_id'], name='fk_rse_resource'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_resource_schedule_exceptions_id_organization')
    )
    op.create_index(op.f('ix_resource_schedule_exceptions_branch_id'), 'resource_schedule_exceptions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_resource_schedule_exceptions_exception_date'), 'resource_schedule_exceptions', ['exception_date'], unique=False)
    op.create_index(op.f('ix_resource_schedule_exceptions_organization_id'), 'resource_schedule_exceptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_resource_schedule_exceptions_resource_id'), 'resource_schedule_exceptions', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_schedule_exceptions_resource_id'), table_name='resource_schedule_exceptions')
    op.drop_index(op.f('ix_resource_schedule_exceptions_organization_id'), table_name='resource_schedule_exceptions')
    op.drop_index(op.f('ix_resource_schedule_exceptions_exception_date'), table_name='resource_schedule_exceptions')
    op.drop_index(op.f('ix_resource_schedule_exceptions_branch_id'), table_name='resource_schedule_exceptions')
    op.drop_table('resource_schedule_exceptions')
    # ### end Alembic commands ###
