"""create role assignments

Revision ID: 924fac38cd04
Revises: 6a9638ff56e2
Create Date: 2026-09-18 13:27:27.375326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924fac38cd04'
down_revision: Union[str, Sequence[str], None] = '6a9638ff56e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_unique_constraint('uq_branches_id_organization', 'branches', ['id', 'organization_id'])
    
    op.create_table('role_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id', 'organization_id'], ['branches.id', 'branches.organization_id'], name='fk_role_assignments_branch_same_org'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id', 'organization_id'], ['users.id', 'users.organization_id'], name='fk_role_assignments_user_same_org'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_assignments_branch_id'), 'role_assignments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_organization_id'), 'role_assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_role_id'), 'role_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_user_id'), 'role_assignments', ['user_id'], unique=False)
    op.create_index('uq_role_assignments_active_branch', 'role_assignments', ['organization_id', 'user_id', 'role_id', 'branch_id'], unique=True, postgresql_where=sa.text("branch_id IS NOT NULL AND status = 'ACTIVE'"))
    op.create_index('uq_role_assignments_active_org', 'role_assignments', ['organization_id', 'user_id', 'role_id'], unique=True, postgresql_where=sa.text("branch_id IS NULL AND status = 'ACTIVE'"))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """Downgrade schema."""
    op.drop_index(
        'uq_role_assignments_active_org',
        table_name='role_assignments',
        postgresql_where=sa.text(
            "branch_id IS NULL AND status = 'ACTIVE'"
        ),
    )

    op.drop_index(
        'uq_role_assignments_active_branch',
        table_name='role_assignments',
        postgresql_where=sa.text(
            "branch_id IS NOT NULL AND status = 'ACTIVE'"
        ),
    )

    op.drop_index(
        op.f('ix_role_assignments_user_id'),
        table_name='role_assignments',
    )
    op.drop_index(
        op.f('ix_role_assignments_role_id'),
        table_name='role_assignments',
    )
    op.drop_index(
        op.f('ix_role_assignments_organization_id'),
        table_name='role_assignments',
    )
    op.drop_index(
        op.f('ix_role_assignments_branch_id'),
        table_name='role_assignments',
    )

    op.drop_table('role_assignments')

    op.drop_constraint(
        'uq_branches_id_organization',
        'branches',
        type_='unique',
    )
    # ### end Alembic commands ###
