"""add branch service resource requirements

Revision ID: 977dbaf3b4b3
Revises: 30795ed0578e
Create Date: 2026-09-21 16:26:05.404976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977dbaf3b4b3'
down_revision: Union[str, Sequence[str], None] = '30795ed0578e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint('uq_branch_services_id_organization_branch', 'branch_services', ['id', 'organization_id', 'branch_id'])
    op.create_unique_constraint('uq_resources_id_organization_branch', 'resources', ['id', 'organization_id', 'branch_id'])
    
    op.create_table('branch_service_resource_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('branch_service_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('required_count > 0', name='ck_branch_service_resource_requirements_required_count'),
    sa.ForeignKeyConstraint(['branch_service_id', 'organization_id', 'branch_id'], ['branch_services.id', 'branch_services.organization_id', 'branch_services.branch_id'], name='fk_bsr_requirements_branch_service'),
    sa.ForeignKeyConstraint(['resource_id', 'organization_id', 'branch_id'], ['resources.id', 'resources.organization_id', 'resources.branch_id'], name='fk_branch_service_resource_requirements_resource_same_branch'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_branch_service_resource_requirements_id_organization'),
    sa.UniqueConstraint('organization_id', 'branch_id', 'branch_service_id', 'resource_id', name='uq_branch_service_resource_requirements_service_resource')
    )
    op.create_index(op.f('ix_branch_service_resource_requirements_branch_id'), 'branch_service_resource_requirements', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_service_resource_requirements_branch_service_id'), 'branch_service_resource_requirements', ['branch_service_id'], unique=False)
    op.create_index(op.f('ix_branch_service_resource_requirements_organization_id'), 'branch_service_resource_requirements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_branch_service_resource_requirements_resource_id'), 'branch_service_resource_requirements', ['resource_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_branch_service_resource_requirements_resource_id'), table_name='branch_service_resource_requirements')
    op.drop_index(op.f('ix_branch_service_resource_requirements_organization_id'), table_name='branch_service_resource_requirements')
    op.drop_index(op.f('ix_branch_service_resource_requirements_branch_service_id'), table_name='branch_service_resource_requirements')
    op.drop_index(op.f('ix_branch_service_resource_requirements_branch_id'), table_name='branch_service_resource_requirements')
    op.drop_table('branch_service_resource_requirements')
    op.drop_constraint('uq_resources_id_organization_branch', 'resources', type_='unique')
    op.drop_constraint('uq_branch_services_id_organization_branch', 'branch_services', type_='unique')
    # ### end Alembic commands ###
