"""add branch services

Revision ID: 9f5125f65991
Revises: 7ee5b1333234
Create Date: 2026-09-21 15:19:09.989752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5125f65991'
down_revision: Union[str, Sequence[str], None] = '7ee5b1333234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id', 'organization_id'], ['branches.id', 'branches.organization_id'], name='fk_branch_services_branch_same_org'),
    sa.ForeignKeyConstraint(['service_id', 'organization_id'], ['services.id', 'services.organization_id'], name='fk_branch_services_service_same_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_branch_services_id_organization'),
    sa.UniqueConstraint('organization_id', 'branch_id', 'service_id', name='uq_branch_services_branch_service')
    )
    op.create_index(op.f('ix_branch_services_branch_id'), 'branch_services', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_services_organization_id'), 'branch_services', ['organization_id'], unique=False)
    op.create_index(op.f('ix_branch_services_service_id'), 'branch_services', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branch_services_service_id'), table_name='branch_services')
    op.drop_index(op.f('ix_branch_services_organization_id'), table_name='branch_services')
    op.drop_index(op.f('ix_branch_services_branch_id'), table_name='branch_services')
    op.drop_table('branch_services')
    # ### end Alembic commands ###
