"""add branch holidays

Revision ID: a021e915bfc2
Revises: 63907bd65380
Create Date: 2026-09-21 15:42:41.601791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a021e915bfc2'
down_revision: Union[str, Sequence[str], None] = '63907bd65380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_holidays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id', 'organization_id'], ['branches.id', 'branches.organization_id'], name='fk_branch_holidays_branch_same_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_branch_holidays_id_organization'),
    sa.UniqueConstraint('organization_id', 'branch_id', 'holiday_date', name='uq_branch_holidays_branch_date')
    )
    op.create_index(op.f('ix_branch_holidays_branch_id'), 'branch_holidays', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_holidays_organization_id'), 'branch_holidays', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branch_holidays_organization_id'), table_name='branch_holidays')
    op.drop_index(op.f('ix_branch_holidays_branch_id'), table_name='branch_holidays')
    op.drop_table('branch_holidays')
    # ### end Alembic commands ###
