"""create employee branch assignments

Revision ID: ae86fa97719c
Revises: ee6fa9b1afe5
Create Date: 2026-09-21 10:43:17.269940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae86fa97719c'
down_revision: Union[str, Sequence[str], None] = 'ee6fa9b1afe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_branch_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id', 'organization_id'], ['branches.id', 'branches.organization_id'], name='fk_employee_branch_assignments_branch_same_org'),
    sa.ForeignKeyConstraint(['employee_id', 'organization_id'], ['employees.id', 'employees.organization_id'], name='fk_employee_branch_assignments_employee_same_org'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_branch_assignments_branch_id'), 'employee_branch_assignments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_employee_branch_assignments_employee_id'), 'employee_branch_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_branch_assignments_organization_id'), 'employee_branch_assignments', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_branch_assignments_organization_id'), table_name='employee_branch_assignments')
    op.drop_index(op.f('ix_employee_branch_assignments_employee_id'), table_name='employee_branch_assignments')
    op.drop_index(op.f('ix_employee_branch_assignments_branch_id'), table_name='employee_branch_assignments')
    op.drop_table('employee_branch_assignments')
    # ### end Alembic commands ###
