"""add employee work schedules

Revision ID: aeeb6f4a2512
Revises: a021e915bfc2
Create Date: 2026-09-21 15:52:04.178898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeeb6f4a2512'
down_revision: Union[str, Sequence[str], None] = 'a021e915bfc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_work_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='ck_employee_work_schedules_day_of_week'),
    sa.CheckConstraint('starts_at < ends_at', name='ck_employee_work_schedules_times'),
    sa.ForeignKeyConstraint(['branch_id', 'organization_id'], ['branches.id', 'branches.organization_id'], name='fk_employee_work_schedules_branch_same_org'),
    sa.ForeignKeyConstraint(['employee_id', 'organization_id'], ['employees.id', 'employees.organization_id'], name='fk_employee_work_schedules_employee_same_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_employee_work_schedules_id_organization')
    )
    op.create_index(op.f('ix_employee_work_schedules_branch_id'), 'employee_work_schedules', ['branch_id'], unique=False)
    op.create_index(op.f('ix_employee_work_schedules_employee_id'), 'employee_work_schedules', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_work_schedules_organization_id'), 'employee_work_schedules', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_work_schedules_organization_id'), table_name='employee_work_schedules')
    op.drop_index(op.f('ix_employee_work_schedules_employee_id'), table_name='employee_work_schedules')
    op.drop_index(op.f('ix_employee_work_schedules_branch_id'), table_name='employee_work_schedules')
    op.drop_table('employee_work_schedules')
    # ### end Alembic commands ###
