"""add appointment service resources

Revision ID: b2ee3d674814
Revises: 465e76903ada
Create Date: 2026-09-21 17:14:28.119230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ee3d674814'
down_revision: Union[str, Sequence[str], None] = '465e76903ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_service_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('appointment_service_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_service_id', 'organization_id'], ['appointment_services.id', 'appointment_services.organization_id'], name='fk_appointment_service_resources_service'),
    sa.ForeignKeyConstraint(['branch_id', 'organization_id'], ['branches.id', 'branches.organization_id'], name='fk_appointment_service_resources_branch'),
    sa.ForeignKeyConstraint(['resource_id', 'organization_id', 'branch_id'], ['resources.id', 'resources.organization_id', 'resources.branch_id'], name='fk_appointment_service_resources_resource'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_appointment_service_resources_id_organization'),
    sa.UniqueConstraint('organization_id', 'appointment_service_id', 'resource_id', name='uq_appointment_service_resources_service_resource')
    )
    op.create_index(op.f('ix_appointment_service_resources_appointment_service_id'), 'appointment_service_resources', ['appointment_service_id'], unique=False)
    op.create_index(op.f('ix_appointment_service_resources_branch_id'), 'appointment_service_resources', ['branch_id'], unique=False)
    op.create_index(op.f('ix_appointment_service_resources_organization_id'), 'appointment_service_resources', ['organization_id'], unique=False)
    op.create_index(op.f('ix_appointment_service_resources_resource_id'), 'appointment_service_resources', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_service_resources_resource_id'), table_name='appointment_service_resources')
    op.drop_index(op.f('ix_appointment_service_resources_organization_id'), table_name='appointment_service_resources')
    op.drop_index(op.f('ix_appointment_service_resources_branch_id'), table_name='appointment_service_resources')
    op.drop_index(op.f('ix_appointment_service_resources_appointment_service_id'), table_name='appointment_service_resources')
    op.drop_table('appointment_service_resources')
    # ### end Alembic commands ###

