"""add appointment cancellation details

Revision ID: b6f32d40dcce
Revises: 97577af73471
Create Date: 2026-09-21 19:43:50.690153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f32d40dcce'
down_revision: Union[str, Sequence[str], None] = '97577af73471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True))
    op.add_column('appointments', sa.Column('cancellation_reason', sa.String(), nullable=True))
    op.create_index(op.f('ix_appointments_cancelled_by_user_id'), 'appointments', ['cancelled_by_user_id'], unique=False)
    op.create_foreign_key('fk_appointments_cancelled_by_user', 'appointments', 'users', ['cancelled_by_user_id', 'organization_id'], ['id', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_appointments_cancelled_by_user', 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_cancelled_by_user_id'), table_name='appointments')
    op.drop_column('appointments', 'cancellation_reason')
    op.drop_column('appointments', 'cancelled_by_user_id')
    op.drop_column('appointments', 'cancelled_at')
    # ### end Alembic commands ###
