"""add appointments

Revision ID: c2335207f47e
Revises: 90c13ac40567
Create Date: 2026-09-21 16:57:57.875767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2335207f47e'
down_revision: Union[str, Sequence[str], None] = '90c13ac40567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('appointment_number', sa.String(length=50), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'BOOKED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointment_status'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('scheduled_start < scheduled_end', name='ck_appointments_schedule_times'),
    sa.ForeignKeyConstraint(['branch_id', 'organization_id'], ['branches.id', 'branches.organization_id'], name='fk_appointments_branch'),
    sa.ForeignKeyConstraint(['customer_id', 'organization_id'], ['customers.id', 'customers.organization_id'], name='fk_appointments_customer'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_appointments_id_organization')
    )
    op.create_index(op.f('ix_appointments_appointment_number'), 'appointments', ['appointment_number'], unique=False)
    op.create_index(op.f('ix_appointments_branch_id'), 'appointments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_appointments_organization_id'), 'appointments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_end'), 'appointments', ['scheduled_end'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_start'), 'appointments', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_start'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_end'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_organization_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_customer_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_branch_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_number'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
