"""add service categories

Revision ID: cf99ee648d63
Revises: 72b6b7897120
Create Date: 2026-09-21 12:41:31.504964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf99ee648d63'
down_revision: Union[str, Sequence[str], None] = '72b6b7897120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_service_categories_id_organization'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_service_categories_organization_code'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_service_categories_organization_name')
    )
    op.create_index(op.f('ix_service_categories_organization_id'), 'service_categories', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_categories_organization_id'), table_name='service_categories')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
