"""create employee designations

Revision ID: ee6fa9b1afe5
Revises: 816cc8b730eb
Create Date: 2026-09-18 15:50:02.712286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6fa9b1afe5'
down_revision: Union[str, Sequence[str], None] = '816cc8b730eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_designations_id_organization', 'designations', ['id', 'organization_id'])
    op.create_unique_constraint(
        'uq_employees_id_organization',
        'employees',
        ['id', 'organization_id']
    )
    op.create_table('employee_designations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('designation_id', sa.UUID(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['designation_id', 'organization_id'], ['designations.id', 'designations.organization_id'], name='fk_employee_designations_designation_same_org'),
    sa.ForeignKeyConstraint(['employee_id', 'organization_id'], ['employees.id', 'employees.organization_id'], name='fk_employee_designations_employee_same_org'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_designations_designation_id'), 'employee_designations', ['designation_id'], unique=False)
    op.create_index(op.f('ix_employee_designations_employee_id'), 'employee_designations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_designations_organization_id'), 'employee_designations', ['organization_id'], unique=False)
    op.create_index('uq_employee_designations_active', 'employee_designations', ['organization_id', 'employee_id'], unique=True, postgresql_where=sa.text('to_date IS NULL'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        'uq_employee_designations_active',
        table_name='employee_designations',
        postgresql_where=sa.text('to_date IS NULL'),
    )

    op.drop_index(
        op.f('ix_employee_designations_organization_id'),
        table_name='employee_designations',
    )

    op.drop_index(
        op.f('ix_employee_designations_employee_id'),
        table_name='employee_designations',
    )

    op.drop_index(
        op.f('ix_employee_designations_designation_id'),
        table_name='employee_designations',
    )

    op.drop_table('employee_designations')

    op.drop_constraint(
        'uq_designations_id_organization',
        'designations',
        type_='unique',
    )

    op.drop_constraint(
        'uq_employees_id_organization',
        'employees',
        type_='unique',
    )